[package]
name = "png_data2"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10.3"
argon2 = "0.5.3"
bitvec = "1.0.1"
getopts = "0.2.21"
png = "0.17.13"
rand = "0.8.5"
rand_chacha = "0.3.1"
